const db=require('../db');const {DIFFICULTIES}=require('../data/content');const ACTIONS_PER_HOUR=2,NIGHT_START=19,NIGHT_END=6;
function alive(r,u){const p=r&&db.getPlayer(r.id,u);if(!r||r.state!=='ACTIVE')return{ok:false,reason:'No active outbreak.'};if(!p||p.state!=='ALIVE')return{ok:false,reason:`You cannot do that while ${p?.state||'missing'}.`};return{ok:true,p}}
function isNight(r){return r.time>=NIGHT_START||r.time<NIGHT_END}
function addNoise(r,a,src='Action'){r.noise=Math.max(0,Math.min(100,(r.noise||0)+a));if(r.noise>=100&&!r.horde){r.horde={eta:2,waves:3};r.feed.unshift(`🚨 HORDE ALERT! ${src} pushed Noise to 100.`)}return r.noise}
function tickDowned(r){for(const u of r.players){const p=db.getPlayer(r.id,u);if(p?.state==='DOWNED'){p.downTicks--;if(p.downTicks<=0){p.state='DEAD';db.addStats(u,{deaths:1});r.feed.unshift(`☠️ <@${u}> bled out.`)}db.setPlayer(r.id,u,p)}}}
function drain(r){for(const u of r.players){const p=db.getPlayer(r.id,u);if(!p||p.state!=='ALIVE')continue;const m=p.role==='survivalist'?.5:1;p.hunger=Math.max(0,p.hunger-2*m);p.water=Math.max(0,p.water-3*m);if(p.hunger===0)p.hp=Math.max(0,p.hp-3);if(p.water===0)p.hp=Math.max(0,p.hp-5);if(p.hp<=0){p.state='DOWNED';p.downTicks=3}db.setPlayer(r.id,u,p)}}
function consumeAction(r,u,cost=1,noise=0,label='Action'){for(let i=0;i<cost;i++){r.turn++;r.actionClock++;tickDowned(r);if(noise)addNoise(r,noise,label);if(r.horde){r.horde.eta--;if(r.horde.eta<=0){r.hordeActive=true;r.horde.eta=0}}if(r.actionClock>=ACTIONS_PER_HOUR){r.actionClock=0;r.time++;if(r.time>=24){r.time=0;r.day++;r.feed.unshift(`☀️ DAY ${r.day}`)}if(r.time===NIGHT_START)r.feed.unshift('🌙 NIGHTFALL — infected aggression increased.');if(r.time===NIGHT_END)r.feed.unshift('☀️ DAWN — night threat subsides.')}drain(r);if(r.extraction?.active&&!r.extraction.ready){r.extraction.eta--;if(r.extraction.eta<=0)r.extraction.ready=true}}db.saveRun(r);return{time:r.time,day:r.day,noise:r.noise,hordeActive:!!r.hordeActive}}
function damagePlayer(r,u,dmg,inf=0){const p=db.getPlayer(r.id,u);if(!p||p.state!=='ALIVE')return null;let d=Math.max(0,Math.round(dmg)),a=Math.min(p.armor,d);p.armor-=a;d-=a;const h=Math.min(p.hp,d);p.hp-=h;p.infection=Math.min(100,p.infection+inf*(DIFFICULTIES[r.difficulty]?.infection||1));if(p.hp<=0||p.infection>=100){p.state='DOWNED';p.downTicks=3}db.setPlayer(r.id,u,p);return{armor:a,health:h,infection:p.infection,state:p.state}}
function results(r){const rows=r.players.map(u=>{const p=db.getPlayer(r.id,u);return{uid:u,kills:p?.kills||0,damage:p?.damage||0,infection:p?.infection||0,state:p?.state||'DEAD',loot:(p?.backpack||[]).length}}).sort((a,b)=>b.kills-a.kills||b.damage-a.damage);return{players:rows,mvp:rows[0]?.uid||null,day:r.day,turn:r.turn}}
function victory(r){r.results=results(r);for(const u of r.players)db.addStats(u,{wins:1,escapes:1,runs:1,xp:1200,lootExtracted:(db.getPlayer(r.id,u)?.backpack||[]).length});db.completeRun(r,true);return{victory:true}}
function defeat(r){r.results=results(r);for(const u of r.players)db.addStats(u,{runs:1});db.completeRun(r,false);return{defeat:true}}
function finishIfDead(r){const canContinue=r.players.some(u=>{const p=db.getPlayer(r.id,u);return p&&['ALIVE','DOWNED'].includes(p.state)});return canContinue?false:defeat(r)}
module.exports={ACTIONS_PER_HOUR,NIGHT_START,NIGHT_END,alive,isNight,addNoise,consumeAction,damagePlayer,results,victory,defeat,finishIfDead};