const {SlashCommandBuilder,EmbedBuilder,MessageFlags}=require('discord.js');const db=require('../db');const {ROLES,LOCATIONS,DIFFICULTIES,ITEMS}=require('../data/content');const runEngine=require('../game/runEngine'),loot=require('../game/lootEngine'),combat=require('../game/combatEngine'),infected=require('../game/infectedEngine'),missions=require('../game/missionEngine'),crafting=require('../game/craftingEngine');const eph=MessageFlags.Ephemeral;
function active(u){const r=db.activeRunForUser(u);return r?.state==='ACTIVE'?r:null}function choices(o){return Object.entries(o).map(([value,x])=>({name:`${x.emoji||''} ${x.name}`.trim(),value}))}
function clock(r){const h=((r.time+11)%12)+1,ap=r.time>=12?'PM':'AM';return `${h}:00 ${ap}`}function enemyText(r){return r.enemy?infected.living(r.enemy).map(z=>`${z.emoji} **${z.id} ${z.name}** ❤️${z.hp}/${z.maxHp}`).join('\n'):'No infected engaged.'}
function hud(r,u){const p=db.getPlayer(r.id,u),loc=LOCATIONS[p.location],s=db.getSquadByUser(u);return new EmbedBuilder().setTitle(`🧟 ZOMBIE OUTBREAK • DAY ${r.day}`).setColor(runEngine.isNight(r)?'#5B21B6':'#22C55E').setDescription(`${runEngine.isNight(r)?'🌙':'☀️'} **${clock(r)}** • ${r.weather}\n${loc.emoji} **${loc.name}**\n🔊 Noise **${r.noise}/100**${r.horde?` • 🚨 Horde ${r.hordeActive?'ACTIVE':`in ${r.horde.eta} actions`}`:''}\n📦 Caches **${r.locationLoot[p.location]??0}**\n\n${enemyText(r)}`).addFields({name:'Survivor',value:`${ROLES[p.role].emoji} **${ROLES[p.role].name}**\n❤️ ${p.hp}/${p.maxHp} 🛡️ ${p.armor}/${p.maxArmor}\n🦠 ${Math.round(p.infection)}% • 🍖${Math.round(p.hunger)} • 💧${Math.round(p.water)}\n🔫 ${p.weapon.id} [${p.weapon.rarity}]\n📦 L:${p.ammo.LIGHT} R:${p.ammo.RIFLE} S:${p.ammo.SHELL}\n🎒 ${p.backpack.length}/${p.backpackSize}`,inline:true},{name:'Mission',value:p.mission?`${p.mission.emoji} ${p.mission.name} ${p.mission.progress}/${p.mission.goal}`:'None',inline:true},{name:'Squad',value:s?s.players.map(id=>{const q=db.getPlayer(r.id,id);return `<@${id}> ${q?.state==='ALIVE'?'🟢':q?.state==='DOWNED'?'🩸':'☠️'} ❤️${q?.hp||0} 🦠${Math.round(q?.infection||0)}%`}).join('\n'):'Solo'})}
function progress(r,u,type,amt=1){const p=db.getPlayer(r.id,u);if(!p?.mission||p.mission.type!==type)return null;p.mission.progress+=amt;if(p.mission.progress>=p.mission.goal){const m={...p.mission};p.mission=null;db.addStats(u,{missions:1,xp:m.xp});db.setPlayer(r.id,u,p);return m}db.setPlayer(r.id,u,p);return null}
module.exports={data:new SlashCommandBuilder().setName('zombie').setDescription('Zombie Outbreak')
.addSubcommand(s=>s.setName('start').setDescription('Create lobby').addStringOption(o=>o.setName('difficulty').setDescription('Difficulty').addChoices(...choices(DIFFICULTIES))))
.addSubcommand(s=>s.setName('join').setDescription('Join lobby')).addSubcommand(s=>s.setName('deploy').setDescription('Deploy squad')).addSubcommand(s=>s.setName('status').setDescription('Survival HUD')).addSubcommand(s=>s.setName('map').setDescription('City map'))
.addSubcommand(s=>s.setName('role').setDescription('Choose/view class').addStringOption(o=>o.setName('role').setDescription('Role').addChoices(...choices(ROLES))))
.addSubcommand(s=>s.setName('search').setDescription('Scavenge')).addSubcommand(s=>s.setName('move').setDescription('Move').addStringOption(o=>o.setName('location').setRequired(true).setDescription('Destination').addChoices(...choices(LOCATIONS))))
.addSubcommand(s=>s.setName('attack').setDescription('Fight infected').addStringOption(o=>o.setName('action').setDescription('Action').addChoices({name:'Shoot',value:'shoot'},{name:'Melee',value:'melee'},{name:'Hide',value:'hide'})).addStringOption(o=>o.setName('target').setDescription('Target ID')))
.addSubcommand(s=>s.setName('mission').setDescription('Take mission')).addSubcommand(s=>s.setName('heal').setDescription('Use medicine').addStringOption(o=>o.setName('item').setRequired(true).setDescription('Medicine').addChoices({name:'Bandage',value:'BANDAGE'},{name:'Medkit',value:'MEDKIT'},{name:'Antiviral',value:'ANTIVIRAL'})))
.addSubcommand(s=>s.setName('eat').setDescription('Eat')).addSubcommand(s=>s.setName('drink').setDescription('Drink')).addSubcommand(s=>s.setName('revive').setDescription('Revive teammate').addUserOption(o=>o.setName('player').setRequired(true).setDescription('Teammate')))
.addSubcommand(s=>s.setName('barricade').setDescription('Build barricade')).addSubcommand(s=>s.setName('craft').setDescription('Craft').addStringOption(o=>o.setName('recipe').setRequired(true).setDescription('Recipe').addChoices({name:'Bandage',value:'BANDAGE'},{name:'Molotov',value:'MOLOTOV'},{name:'Barricade Kit',value:'BARRICADE'})))
.addSubcommand(s=>s.setName('extract').setDescription('Call/board extraction')).addSubcommand(s=>s.setName('history').setDescription('Last run')),
async execute(i){const sub=i.options.getSubcommand(),u=i.user.id,g=i.guildId;
if(sub==='start'){if(db.activeRunForUser(u))return i.reply({content:'Already in an outbreak.',flags:eph});if(db.getLobby(g))return i.reply({content:'A lobby already exists. Use /zombie join.',flags:eph});const r=db.createRun(g,u,i.options.getString('difficulty')||'OUTBREAK');db.createSquad(r.id,u);r.locationLoot=Object.fromEntries(Object.entries(LOCATIONS).map(([k,v])=>[k,v.caches]));db.saveRun(r);return i.reply(`🧟 Outbreak lobby created — **${DIFFICULTIES[r.difficulty].name}**.`)}
if(sub==='join'){if(db.activeRunForUser(u))return i.reply({content:'Already in a run.',flags:eph});const r=db.getLobby(g);if(!r)return i.reply({content:'No lobby.',flags:eph});const s=db.getSquads(r.id)[0];if(!s||!db.addPlayer(s.id,u))return i.reply({content:'Squad full.',flags:eph});if(!r.players.includes(u))r.players.push(u);db.saveRun(r);return i.reply(`🧟 Joined survivor squad (${s.players.length}/4).`)}
const r=db.activeRunForUser(u);
if(sub==='deploy'){const s=db.getSquadByUser(u);if(!r||r.state!=='LOBBY'||r.hostId!==u)return i.reply({content:'Only host can deploy.',flags:eph});if(!db.allReady(s))return i.reply({content:'Everyone must /squad ready first.',flags:eph});r.state='ACTIVE';for(const id of r.players){const p=db.getPlayer(r.id,id);p.location='APARTMENTS';db.setPlayer(r.id,id,p)}db.saveRun(r);return i.reply({embeds:[hud(r,u).setTitle('🪂 OUTBREAK DEPLOYED') ]})}
if(!r)return i.reply({content:'No active outbreak.',flags:eph});
if(sub==='status')return i.reply({embeds:[hud(r,u)]});
if(sub==='map'){const p=db.getPlayer(r.id,u);return i.reply({embeds:[new EmbedBuilder().setTitle('🗺️ QUARANTINE CITY').setDescription(Object.entries(LOCATIONS).map(([k,x])=>`${k===p.location?'➡️':'•'} ${x.emoji} **${x.name}** • 📦${r.locationLoot[k]??0} • danger x${x.danger}`).join('\n'))]})}
if(sub==='role'){const role=i.options.getString('role');if(!role)return i.reply({embeds:[new EmbedBuilder().setTitle('🧍 SURVIVOR CLASSES').setDescription(Object.entries(ROLES).map(([k,x])=>`${x.emoji} **${x.name}** — ${x.description}`).join('\n'))]});if(r.state!=='LOBBY')return i.reply({content:'Roles lock after deployment.',flags:eph});const p=db.getPlayer(r.id,u);p.role=role;db.setPlayer(r.id,u,p);db.setReady(u,false);return i.reply(`${ROLES[role].emoji} Role set to **${ROLES[role].name}**.`)}
const ag=runEngine.alive(r,u);if(['search','move','attack','mission','heal','eat','drink','barricade','craft','extract'].includes(sub)&&!ag.ok)return i.reply({content:ag.reason,flags:eph});const p=ag.p;
if(sub==='search'){if(p.pendingLoot)return i.reply({content:'Resolve pending loot first.',flags:eph});if((r.locationLoot[p.location]||0)<=0)return i.reply({content:'This location is picked clean.',flags:eph});r.locationLoot[p.location]--;const res=loot.search(r,p),m=progress(r,u,'search');db.setPlayer(r.id,u,p);runEngine.consumeAction(r,u,1,Math.max(1,LOCATIONS[p.location].noise-(p.role==='scout'?2:0)),'Search');return i.reply(`🔍 ${res.found.map(x=>`${x.emoji||'📦'} ${x.name}`).join(', ')||'Nothing'}${res.pending?` • ⚠️ Pending ${res.pending.name}`:''}${m?` • ✅ ${m.name} complete`:''}\n🔊 Noise ${r.noise}/100`)}
if(sub==='move'){const d=i.options.getString('location');if(d===p.location)return i.reply({content:'Already there.',flags:eph});p.location=d;db.setPlayer(r.id,u,p);runEngine.consumeAction(r,u,1,p.role==='scout'?1:3,'Travel');return i.reply(`${LOCATIONS[d].emoji} Moved to **${LOCATIONS[d].name}**. 🔊 ${r.noise}/100`)}
if(sub==='attack'){const before=p.kills,res=combat.fight(r,u,i.options.getString('action')||'shoot',i.options.getString('target'));if(!res.success)return i.reply({content:res.reason,flags:eph});const fresh=db.getPlayer(r.id,u),d=fresh.kills-before;if(d)progress(r,u,'kill',d);let txt=res.summary;if(res.counter)txt+=`\n🧟 Counterattack: ${res.counter.health+res.counter.armor} damage • Infection ${Math.round(res.counter.infection)}%`;return i.reply({embeds:[hud(r,u).setDescription(txt)]})}
if(sub==='mission'){if(p.mission)return i.reply({content:'You already have a mission.',flags:eph});p.mission=missions.random();db.setPlayer(r.id,u,p);return i.reply(`${p.mission.emoji} **${p.mission.name}** — ${p.mission.description}\nReward: ${p.mission.reward} supplies + ${p.mission.xp} XP`)}
if(sub==='heal'){const id=i.options.getString('item'),idx=p.backpack.findIndex(x=>x.id===id);if(idx<0)return i.reply({content:`You don't have ${id}.`,flags:eph});if(id==='BANDAGE')p.hp=Math.min(100,p.hp+(p.role==='medic'?35:25));if(id==='MEDKIT')p.hp=Math.min(100,p.hp+(p.role==='medic'?80:60));if(id==='ANTIVIRAL')p.infection=Math.max(0,p.infection-(p.role==='medic'?45:30));p.backpack.splice(idx,1);db.setPlayer(r.id,u,p);runEngine.consumeAction(r,u,1,0,'Heal');return i.reply(`💉 Used **${ITEMS[id].name}**. ❤️${p.hp} 🦠${Math.round(p.infection)}%`)}
if(sub==='eat'){const idx=p.backpack.findIndex(x=>x.id==='FOOD');if(idx<0)return i.reply({content:'No Food Ration.',flags:eph});p.backpack.splice(idx,1);p.hunger=Math.min(100,p.hunger+40);db.setPlayer(r.id,u,p);return i.reply(`🥫 Hunger ${Math.round(p.hunger)}.`)}
if(sub==='drink'){const idx=p.backpack.findIndex(x=>x.id==='WATER');if(idx<0)return i.reply({content:'No Water Bottle.',flags:eph});p.backpack.splice(idx,1);p.water=Math.min(100,p.water+50);db.setPlayer(r.id,u,p);return i.reply(`💧 Hydration ${Math.round(p.water)}.`)}
if(sub==='revive'){const t=i.options.getUser('player'),tp=db.getPlayer(r.id,t.id);if(!tp||tp.state!=='DOWNED'||!db.getSquadByUser(u).players.includes(t.id))return i.reply({content:'Teammate is not downed.',flags:eph});tp.state='ALIVE';tp.hp=p.role==='medic'?55:30;tp.downTicks=3;db.setPlayer(r.id,t.id,tp);db.addStats(u,{revives:1,xp:100});runEngine.consumeAction(r,u,1,0,'Revive');return i.reply(`💉 Revived <@${t.id}> to ${tp.hp} HP.`)}
if(sub==='barricade'){const idx=p.backpack.findIndex(x=>x.id==='TOOLKIT');if(idx<0)return i.reply({content:'Need a Toolkit.',flags:eph});p.backpack.splice(idx,1);const a=p.role==='engineer'?45:30;p.barricade=Math.min(100,p.barricade+a);db.setPlayer(r.id,u,p);runEngine.consumeAction(r,u,1,2,'Barricade');return i.reply(`🚧 Barricades ${p.barricade}/100.`)}
if(sub==='craft'){const res=crafting.craft(p,i.options.getString('recipe'));if(!res.success)return i.reply({content:res.reason,flags:eph});db.setPlayer(r.id,u,p);runEngine.consumeAction(r,u,1,p.role==='engineer'?1:2,'Craft');return i.reply(`🔧 Crafted **${res.recipe.name}**.`)}
if(sub==='extract'){if(!r.extraction){r.extraction={active:true,eta:5,ready:false,location:'HOSPITAL'};db.saveRun(r);return i.reply('🚁 Extraction inbound to Hospital rooftop in 5 actions.')}if(!r.extraction.ready)return i.reply({content:`Extraction arrives in ${r.extraction.eta} actions.`,flags:eph});if(p.location!=='HOSPITAL')return i.reply({content:'Reach Hospital rooftop.',flags:eph});runEngine.victory(r);return i.reply('🚁 **SUCCESSFUL EXTRACTION!** Your squad escaped.')}
if(sub==='history'){const h=db.lastRun(u);return h?i.reply(`📊 Last run: **${h.state}** • Day ${h.day} • ${h.turn} actions`):i.reply({content:'No history.',flags:eph})}
}};